# Site Description
name: Soncy

# Jekyll Config
markdown: redcarpet
exclude: ['deploy.yml', 'CNAME', 'Gemfile', 'Gemfile.lock']

# Server Config
host: besoncy.dev

# Sass Config
sass:
  sass_dir: assets/_sass
  style: compressed
